name:                deriv
version:             0.1.0.0
github:              "awalterschulze/deriv"
license:             BSD3
author:              "Walter Schulze"
maintainer:          "awalterschulze@gmail.com"
copyright:           "Walter Schulze"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/awalterschulze/deriv#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- containers

library:
  source-dirs: src

executables:
  deriv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deriv

tests:
  deriv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deriv
