// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(3), /* # */
			nil,      /* id */
			nil,      /* = */
			nil,      /* ( */
			nil,      /* | */
			nil,      /* ) */
			nil,      /* [ */
			nil,      /* , */
			nil,      /* ] */
			nil,      /* { */
			nil,      /* ; */
			nil,      /* } */
			nil,      /* * */
			nil,      /* @ */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			shift(3),     /* # */
			nil,          /* id */
			nil,          /* = */
			nil,          /* ( */
			nil,          /* | */
			nil,          /* ) */
			nil,          /* [ */
			nil,          /* , */
			nil,          /* ] */
			nil,          /* { */
			nil,          /* ; */
			nil,          /* } */
			nil,          /* * */
			nil,          /* @ */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Definitions */
			reduce(1), /* #, reduce: Definitions */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* # */
			shift(5), /* id */
			nil,      /* = */
			nil,      /* ( */
			nil,      /* | */
			nil,      /* ) */
			nil,      /* [ */
			nil,      /* , */
			nil,      /* ] */
			nil,      /* { */
			nil,      /* ; */
			nil,      /* } */
			nil,      /* * */
			nil,      /* @ */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: Definitions */
			reduce(2), /* #, reduce: Definitions */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* # */
			nil,      /* id */
			shift(6), /* = */
			nil,      /* ( */
			nil,      /* | */
			nil,      /* ) */
			nil,      /* [ */
			nil,      /* , */
			nil,      /* ] */
			nil,      /* { */
			nil,      /* ; */
			nil,      /* } */
			nil,      /* * */
			nil,      /* @ */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(7),  /* id */
			nil,       /* = */
			shift(9),  /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(10), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(11), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(12), /* @ */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: Expr */
			reduce(9), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: Definition */
			reduce(3), /* #, reduce: Definition */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(31), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(9), /* |, reduce: Expr */
			reduce(9), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			shift(32), /* | */
			shift(33), /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(37), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(9), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			shift(38), /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(42), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(9), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			shift(43), /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(47), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(8), /* $, reduce: Expr */
			reduce(8), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			shift(54), /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			shift(55), /* | */
			shift(56), /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			shift(57), /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			shift(58), /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(8), /* |, reduce: Expr */
			reduce(8), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			shift(65), /* | */
			shift(66), /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			shift(67), /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			shift(68), /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(8), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			shift(75), /* | */
			shift(76), /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			shift(77), /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			shift(78), /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(8), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(9), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			shift(79), /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(83), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(7), /* $, reduce: Expr */
			reduce(7), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			shift(85), /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(9), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			shift(88), /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(92), /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			shift(94), /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(9), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			shift(97), /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(13), /* id */
			nil,       /* = */
			shift(15), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(16), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(17), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(18), /* @ */
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(19), /* id */
			nil,       /* = */
			shift(21), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(22), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(23), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(24), /* @ */
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(25), /* id */
			nil,       /* = */
			shift(27), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(28), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(29), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(30), /* @ */
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			shift(101), /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			shift(103), /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: Expr */
			reduce(4), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			shift(106), /* | */
			shift(107), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			shift(108), /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			shift(109), /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(8), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(110), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(7), /* |, reduce: Expr */
			reduce(7), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(111), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(112), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: Expr */
			reduce(5), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			shift(113), /* | */
			shift(114), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			shift(115), /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			shift(116), /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(8), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(117), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(7), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(118), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(119), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: Expr */
			reduce(6), /* #, reduce: Expr */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			shift(120), /* | */
			shift(121), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			shift(122), /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			shift(123), /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(8), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(124), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(7), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(125), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(126), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			shift(128), /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(4), /* |, reduce: Expr */
			reduce(4), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(5), /* |, reduce: Expr */
			reduce(5), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			reduce(6), /* |, reduce: Expr */
			reduce(6), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			shift(132), /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(4), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(5), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			reduce(6), /* ,, reduce: Expr */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(48), /* id */
			nil,       /* = */
			shift(50), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(51), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(52), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(53), /* @ */
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			shift(136), /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(59), /* id */
			nil,       /* = */
			shift(61), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(62), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(63), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(64), /* @ */
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			shift(69), /* id */
			nil,       /* = */
			shift(71), /* ( */
			nil,       /* | */
			nil,       /* ) */
			shift(72), /* [ */
			nil,       /* , */
			nil,       /* ] */
			shift(73), /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			shift(74), /* @ */
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(4), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(5), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			reduce(6), /* ;, reduce: Expr */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S127
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(139), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S128
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(7), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S129
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(140), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S130
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(141), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S131
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(142), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S132
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(7), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S133
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(143), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S134
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(144), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S135
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			shift(145), /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S136
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(7), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S137
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			shift(146), /* ] */
			nil,        /* { */
			nil,        /* ; */
			nil,        /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S138
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* # */
			nil,        /* id */
			nil,        /* = */
			nil,        /* ( */
			nil,        /* | */
			nil,        /* ) */
			nil,        /* [ */
			nil,        /* , */
			nil,        /* ] */
			nil,        /* { */
			nil,        /* ; */
			shift(147), /* } */
			nil,        /* * */
			nil,        /* @ */
		},
	},
	actionRow{ // S139
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(4), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S140
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(5), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S141
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			reduce(6), /* ), reduce: Expr */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S142
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(4), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S143
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(5), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S144
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			reduce(6), /* ], reduce: Expr */
			nil,       /* { */
			nil,       /* ; */
			nil,       /* } */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S145
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(4), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S146
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(5), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
	actionRow{ // S147
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* # */
			nil,       /* id */
			nil,       /* = */
			nil,       /* ( */
			nil,       /* | */
			nil,       /* ) */
			nil,       /* [ */
			nil,       /* , */
			nil,       /* ] */
			nil,       /* { */
			nil,       /* ; */
			reduce(6), /* }, reduce: Expr */
			nil,       /* * */
			nil,       /* @ */
		},
	},
}
