// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Definitions
		2,  // Definition
		-1, // Expr
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Definitions
		4,  // Definition
		-1, // Expr
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Definitions
		-1, // Definition
		8,  // Expr
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Definitions
		-1, // Definition
		14, // Expr
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Definitions
		-1, // Definition
		20, // Expr
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Definitions
		-1, // Definition
		26, // Expr
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Definitions
		-1, // Definition
		34, // Expr
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Definitions
		-1, // Definition
		35, // Expr
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Definitions
		-1, // Definition
		36, // Expr
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Definitions
		-1, // Definition
		39, // Expr
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Definitions
		-1, // Definition
		40, // Expr
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Definitions
		-1, // Definition
		41, // Expr
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Definitions
		-1, // Definition
		44, // Expr
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Definitions
		-1, // Definition
		45, // Expr
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Definitions
		-1, // Definition
		46, // Expr
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Definitions
		-1, // Definition
		49, // Expr
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Definitions
		-1, // Definition
		60, // Expr
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Definitions
		-1, // Definition
		70, // Expr
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Definitions
		-1, // Definition
		80, // Expr
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Definitions
		-1, // Definition
		81, // Expr
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Definitions
		-1, // Definition
		82, // Expr
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Definitions
		-1, // Definition
		84, // Expr
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Definitions
		-1, // Definition
		86, // Expr
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Definitions
		-1, // Definition
		87, // Expr
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Definitions
		-1, // Definition
		89, // Expr
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Definitions
		-1, // Definition
		90, // Expr
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Definitions
		-1, // Definition
		91, // Expr
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Definitions
		-1, // Definition
		93, // Expr
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Definitions
		-1, // Definition
		95, // Expr
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Definitions
		-1, // Definition
		96, // Expr
	},
	gotoRow{ // S69
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Definitions
		-1, // Definition
		98, // Expr
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Definitions
		-1, // Definition
		99, // Expr
	},
	gotoRow{ // S73
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		100, // Expr
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S75
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		102, // Expr
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S77
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		104, // Expr
	},
	gotoRow{ // S78
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		105, // Expr
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S80
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S83
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S84
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S86
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S89
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S91
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S95
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S96
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S97
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S98
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S99
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S100
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S101
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S102
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S103
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S104
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S105
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S106
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		127, // Expr
	},
	gotoRow{ // S107
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S108
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		129, // Expr
	},
	gotoRow{ // S109
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		130, // Expr
	},
	gotoRow{ // S110
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S111
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S112
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S113
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		131, // Expr
	},
	gotoRow{ // S114
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S115
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		133, // Expr
	},
	gotoRow{ // S116
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		134, // Expr
	},
	gotoRow{ // S117
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S118
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S119
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S120
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		135, // Expr
	},
	gotoRow{ // S121
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S122
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		137, // Expr
	},
	gotoRow{ // S123
		-1,  // S'
		-1,  // Definitions
		-1,  // Definition
		138, // Expr
	},
	gotoRow{ // S124
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S125
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S126
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S127
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S128
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S129
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S130
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S131
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S132
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S133
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S134
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S135
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S136
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S137
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S138
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S139
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S140
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S141
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S142
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S143
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S144
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S145
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S146
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
	gotoRow{ // S147
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
	},
}
