
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Definitions
		2, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Definitions
		4, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S2
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S6
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		8, // Expr
		

	},
	gotoRow{ // S7
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		13, // Expr
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		18, // Expr
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S13
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S14
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		25, // Expr
		

	},
	gotoRow{ // S15
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		26, // Expr
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S19
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		29, // Expr
		

	},
	gotoRow{ // S20
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		30, // Expr
		

	},
	gotoRow{ // S21
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S22
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S23
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		33, // Expr
		

	},
	gotoRow{ // S24
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S25
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S26
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S27
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S28
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		42, // Expr
		

	},
	gotoRow{ // S29
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S30
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S31
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S32
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S33
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S34
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		50, // Expr
		

	},
	gotoRow{ // S35
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		51, // Expr
		

	},
	gotoRow{ // S36
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S37
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S38
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		53, // Expr
		

	},
	gotoRow{ // S39
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S40
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		55, // Expr
		

	},
	gotoRow{ // S41
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S42
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S43
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		57, // Expr
		

	},
	gotoRow{ // S44
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		58, // Expr
		

	},
	gotoRow{ // S45
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S46
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		60, // Expr
		

	},
	gotoRow{ // S47
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S48
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		62, // Expr
		

	},
	gotoRow{ // S49
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S50
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S51
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S52
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S53
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S54
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S55
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S56
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S57
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S58
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S59
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S60
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S61
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S62
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S63
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		73, // Expr
		

	},
	gotoRow{ // S64
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S65
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		75, // Expr
		

	},
	gotoRow{ // S66
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S67
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S68
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		76, // Expr
		

	},
	gotoRow{ // S69
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S70
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		78, // Expr
		

	},
	gotoRow{ // S71
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S72
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S73
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S74
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S75
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S76
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S77
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S78
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S79
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S80
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S81
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	gotoRow{ // S82
		
		-1, // S'
		-1, // Definitions
		-1, // Definition
		-1, // Expr
		

	},
	
}
